LIBFILES = suche.c ../utils/zahlenEingabe.c ../utils/stoppuhr.c ../utils/zufallsarray.c

sucheTest:
	gcc -Wall -o sucheTest sucheTest.c $(LIBFILES)
	
zaehleVorkommen:
	gcc -Wall -o zaehleVorkommen zaehleVorkommen.c $(LIBFILES)